#ifndef MM_ADDRESS_H
#define MM_ADDRESS_H
#define ENTRY_DIR_PAGES       0

#define TOTAL_PAGES 1024
#define NUM_PAG_KERNEL 256
#define PAG_LOG_INIT_CODE_P0 (L_USER_START>>12)
#define FRAME_INIT_CODE_P0 (PH_USER_START>>12)
#define NUM_PAG_CODE 8
#define PAG_LOG_INIT_DATA_P0 (PAG_LOG_INIT_CODE_P0+NUM_PAG_CODE)
#define NUM_PAG_DATA 2
#define PAGE_SIZE 0x1000
#endif

